### PR TITLE
Fixing #2: Move into sub-projects

### PR DESCRIPTION
**Pull request by Swat-SomeBug**
Created 5 sub-projects/packages `gtest`, `gtest-tests`, `gtest-examples`, `gmock` and `gmock-tests.

Utilizing soft-links from upstream to maintain directory structure.

Update upstream version to release-1.10.0

### CODE REVIEW

**Comment by Swat-SomeBug** [comment]
@Klaim there are quite a few bugs in the PR. I’m currently working on the solution. These should not be merged in yet!

**Comment by Klaim** [comment]
> @Klaim there are quite a few bugs in the PR. I’m currently working on the solution. These should not be merged in yet!

Ok!

Note that the main potential comment so far (I only did a quick overview for now) is that I would prefer to make symlinks to directories instead of files, to help with maintenance when they remove and add files. Though it's ok with symlink to files too, it's just my preference.

**Comment by Klaim** [comment]
Looking at the issues, I see mainly on Windows/MSVC that `gmock` doesn't compile because of `dllimport` misuse.
Specifically: https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2491?view=msvc-160
For example in `gmock-cardinalities.cc`: 
```

// Creates a cardinality that allows at least n calls.
GTEST_API_ Cardinality AtLeast(int n) { return Between(n, INT_MAX); }
```

Here `GTEST_API_` should be `dllexport` instead of `dllimport`.

The source of the issue is that `lib{gmock}` depends on `lib{gtest}` which exports `-DGTEST_LINKED_AS_SHARED_LIBRARY=1`, which appears in the compilation commands of `lib{gmock}}` and forces it to mark it's own symbols as `dllimport`.

I see in the CMake they do the same thing (but I didn't try to configure it with CMake yet) so not sure how anyone manage to compile that in shared library mode... maybe nobody does? Ideally the code of `gmock` would use a different macro to distinguish it's own symbols export/import from the ones of `gtest`....

**Comment by Swat-SomeBug** [comment]
I was able to solve the `GTEST_API_` issue and compile both `liba{gmock}` and `libs{gmock}`. However, the solution was not good. The fundamental problem I see that `gtest` and `gmock` are extremely coupled.
When I solve the `GTEST_API_` issue, I still face problems because `lib{gtest}` does not export `testing::internal::ParseInt32` which is referenced by `gmock`. It seems, `gmock` needs to be compiled with along with `gtest`, particularly a dependency on `obj{gtest-port}`.

So my proposal would be to merge `gtest` and `gmock`  packages called `googletest` as before. And as I understand only a single tests package is allowed. So need to merge `gtest-tests` and `gmock-tests` as well calling it `googletest-tests`. We can keep `gtest-samples` as a separate package and for consistency call it `googletest-samples`.
What do you think? I can create a new PR and this one can be rejected.

**Comment by Klaim** [comment]
Would it work if we use a utility library of `gtest`, `libu{gtest}` to compile `lib{gmock}` instead so that `gtest` is built as part of `gmock`?

**Comment by Klaim** [comment]
I'm not at ease with the idea of embarking gmock when I only use gtest, to be clear.

**Comment by Swat-SomeBug** [comment]
I agree, we should have small hopefully atomic libraries. What I understand is we require to compile at least a part of `gtest` sources with different `cxx.poptions` to set `GTEST_API_` appropriately on windows. As I know `libue{}` would not help here as sources are already compiled.
We could include the required `gtest` sources as part of `gmock` to have some decoupling (but remove from it's `depends:` in `manifest`).

**Comment by Klaim** [comment]
Indeed... it's not super clean but that's the cleanest until they fix the mess on their side (their handling of `GTEST_API_` seems totally incorrect to me).

I suppose it's not hard to do this by relying on the symlinks.

**Comment by Swat-SomeBug** [comment]
Hi @Klaim 
I think the PR is now in a good shape. I am able to build all 5 packages on linux, mac and windows with shared only, static only and combination of both. However, with the current version of upstream, I believe tests are failing on windows. I don't see the same failures on linux/macos. Same thing happens with `cmake` builds so it does look like an upstream issue.
Please let me know if you have some feedback for me.

**Comment by Klaim** [comment]
Ok thanks! I'll check the Windows case to be sure (I use it a lot).

Did you already `bdep ci` this PR?

**Comment by Klaim** [comment]
I have looked at the issues with gmock and started doing some modifications and fixes but it will have to wait for next week for me to complete.

Other than these issues, I think the handling of headers could be largely simplified (and avoid multi-scope variable manipulations that in my experience is a bit hard to get right - not sure if its because of bugs though).
I'll try a modification and report soon.

**Comment by Klaim** [comment]
Quick heads-up: I didn't forget this and did several attempts at fixing everything on windows, but I keep hitting issues.
I intent soon to reset my changes to get back to this branch and re-add a few bugfixes which suggests (maybe) build2 bugs on Windows (that I actually already spotted before but wasn't sure about, see my notes in the root directory).
I need more time to figure out some other issues.

**Comment by Swat-SomeBug** [comment]
Cool. Sounds great! For me the PR seems to build very similar to the upstream’s `cmake` build. As mentioned `gmock_tests` still fails. The build itself passes with both shared and static linking. I haven’t checked with `build2` latest though. I remember some differences where builds were failing between latest and 0.13.0.

**Comment by Klaim** [comment]
I'm using stage version and I'll check through stage CI before merging, no problem.

**Comment by Klaim** [comment]
Sorry for the delay, I had to pause progress on this for some time. I will resume my effort this week so that we have everything finally working for `build2` `v0.14.0` release.

**Comment by Klaim** [comment]
I will merge this now, and push my ongoing branch which attempts to fix some issues and gmock (but is not ready yet).

Thanks @Swat-SomeBug !

**Pull request merged**
